services:
    krlove.async.factory:
        class: Krlove\AsyncServiceCallBundle\AsyncServiceFactory
        arguments:
            - '@filesystem'
            - '%kernel.project_dir%'
            - '%krlove_async_service_call.console_path%'
            - '%krlove_async_service_call.php_path%'

    krlove.async:
        factory: ['@Krlove\AsyncServiceCallBundle\AsyncService', 'createAsyncService']
        public: true
